export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';
export const CURRENCY_ADDED = 'CURRENCY_ADDED';
export const CURRENCY_DELETED = 'CURRENCY_DELETED';

